// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: payment.proto

package payment

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StartOrderPaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	OrderId       int64                  `protobuf:"varint,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	FullPrice     int64                  `protobuf:"varint,3,opt,name=full_price,json=fullPrice,proto3" json:"full_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartOrderPaymentRequest) Reset() {
	*x = StartOrderPaymentRequest{}
	mi := &file_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartOrderPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartOrderPaymentRequest) ProtoMessage() {}

func (x *StartOrderPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartOrderPaymentRequest.ProtoReflect.Descriptor instead.
func (*StartOrderPaymentRequest) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{0}
}

func (x *StartOrderPaymentRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *StartOrderPaymentRequest) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *StartOrderPaymentRequest) GetFullPrice() int64 {
	if x != nil {
		return x.FullPrice
	}
	return 0
}

type StartOrderPaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartOrderPaymentResponse) Reset() {
	*x = StartOrderPaymentResponse{}
	mi := &file_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartOrderPaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartOrderPaymentResponse) ProtoMessage() {}

func (x *StartOrderPaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartOrderPaymentResponse.ProtoReflect.Descriptor instead.
func (*StartOrderPaymentResponse) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{1}
}

type CancelOrderPaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	OrderId       int64                  `protobuf:"varint,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderPaymentRequest) Reset() {
	*x = CancelOrderPaymentRequest{}
	mi := &file_payment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderPaymentRequest) ProtoMessage() {}

func (x *CancelOrderPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderPaymentRequest.ProtoReflect.Descriptor instead.
func (*CancelOrderPaymentRequest) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{2}
}

func (x *CancelOrderPaymentRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *CancelOrderPaymentRequest) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

type CancelOrderPaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderPaymentResponse) Reset() {
	*x = CancelOrderPaymentResponse{}
	mi := &file_payment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderPaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderPaymentResponse) ProtoMessage() {}

func (x *CancelOrderPaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderPaymentResponse.ProtoReflect.Descriptor instead.
func (*CancelOrderPaymentResponse) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{3}
}

var File_payment_proto protoreflect.FileDescriptor

const file_payment_proto_rawDesc = "" +
	"\n" +
	"\rpayment.proto\x12\apayment\"j\n" +
	"\x18StartOrderPaymentRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x19\n" +
	"\border_id\x18\x02 \x01(\x03R\aorderId\x12\x1d\n" +
	"\n" +
	"full_price\x18\x03 \x01(\x03R\tfullPrice\"\x1b\n" +
	"\x19StartOrderPaymentResponse\"L\n" +
	"\x19CancelOrderPaymentRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x19\n" +
	"\border_id\x18\x02 \x01(\x03R\aorderId\"\x1c\n" +
	"\x1aCancelOrderPaymentResponse2\xcb\x01\n" +
	"\x0ePaymentService\x12Z\n" +
	"\x11StartOrderPayment\x12!.payment.StartOrderPaymentRequest\x1a\".payment.StartOrderPaymentResponse\x12]\n" +
	"\x12CancelOrderPayment\x12\".payment.CancelOrderPaymentRequest\x1a#.payment.CancelOrderPaymentResponseB\x1bZ\x19base/internal/api/paymentb\x06proto3"

var (
	file_payment_proto_rawDescOnce sync.Once
	file_payment_proto_rawDescData []byte
)

func file_payment_proto_rawDescGZIP() []byte {
	file_payment_proto_rawDescOnce.Do(func() {
		file_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_payment_proto_rawDesc), len(file_payment_proto_rawDesc)))
	})
	return file_payment_proto_rawDescData
}

var file_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_payment_proto_goTypes = []any{
	(*StartOrderPaymentRequest)(nil),   // 0: payment.StartOrderPaymentRequest
	(*StartOrderPaymentResponse)(nil),  // 1: payment.StartOrderPaymentResponse
	(*CancelOrderPaymentRequest)(nil),  // 2: payment.CancelOrderPaymentRequest
	(*CancelOrderPaymentResponse)(nil), // 3: payment.CancelOrderPaymentResponse
}
var file_payment_proto_depIdxs = []int32{
	0, // 0: payment.PaymentService.StartOrderPayment:input_type -> payment.StartOrderPaymentRequest
	2, // 1: payment.PaymentService.CancelOrderPayment:input_type -> payment.CancelOrderPaymentRequest
	1, // 2: payment.PaymentService.StartOrderPayment:output_type -> payment.StartOrderPaymentResponse
	3, // 3: payment.PaymentService.CancelOrderPayment:output_type -> payment.CancelOrderPaymentResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_payment_proto_init() }
func file_payment_proto_init() {
	if File_payment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_payment_proto_rawDesc), len(file_payment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_payment_proto_goTypes,
		DependencyIndexes: file_payment_proto_depIdxs,
		MessageInfos:      file_payment_proto_msgTypes,
	}.Build()
	File_payment_proto = out.File
	file_payment_proto_goTypes = nil
	file_payment_proto_depIdxs = nil
}
