apiVersion: gateway.networking.k8s.io/v1
kind: GRPCRoute
metadata:
  name: {{ .Values.app.name }}-route
  namespace: {{ .Release.Namespace }}
spec:
  parentRefs:
  - name: main-gateway
    namespace: istio-ingress
  hostnames:
  - {{ .Values.domain }}
  rules:
  - matches:
    - method:
        service: {{ .Values.app.name }}.OrderService
        method: CreateOrder
    - method:
        service: {{ .Values.app.name }}.OrderService
        method: GetOrderInfo
    backendRefs:
    - name: {{ .Values.app.name }}-service
      port: 80
