apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}-deployment
  namespace: azazon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
      - name: {{ .Values.app.name }}
        image: {{ .Values.app.name }}-app:latest
        imagePullPolicy: Never
        env:
        - name: VIRTUAL_RUNTIME
          value: "kubernetes"
        ports:
        - name: {{ .Values.app.name  | trunc 10 }}-port
          containerPort: {{ .Values.app.port }}
          protocol: TCP
