apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-service
  namespace: azazon
spec:
  selector:
    app: {{ .Values.app.name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.app.name | trunc 10 }}-port
