apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.app.name }}-database-config
  namespace: azazon
data:
  POSTGRES_DB: {{ .Values.db.name }}
  POSTGRES_USER: {{ .Values.db.user }}
  POSTGRES_PASSWORD: {{ .Values.db.password }}
  postgresql.conf: |
    data_directory = '/data/pgdata'
    hba_file = '/config/pg_hba.conf'
    ident_file = '/config/pg_ident.conf'

    port = {{ .Values.db.port }}
    listen_addresses = '*'
  pg_hba.conf: |
    # TYPE  DATABASE        USER            ADDRESS                 METHOD
    host    all             all             10.244.0.0/16           md5
    # "local" is for Unix domain socket connections only
    local   all             all                                     trust
    # IPv4 local connections:
    host    all             all             127.0.0.1/32            trust
    # IPv6 local connections:
    host    all             all             ::1/128                 trust
    # Allow replication connections from localhost, by a user with the
    # replication privilege.
    local   replication     all                                     trust
    host    replication     all             127.0.0.1/32            trust
    host    replication     all             ::1/128                 trust
