// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package query

type OrderCanceledOutbox struct {
	ID        int32
	Processed bool
	Msg       []byte
}

type OrderConfirmedOutbox struct {
	ID        int32
	Processed bool
	Msg       []byte
}

type ProcessedPayment struct {
	ID      int32
	OrderID int32
}
