// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: payment.sql

package query

import (
	"context"
)

const createProcessedPayment = `-- name: CreateProcessedPayment :exec
INSERT INTO processed_payment (order_id)
VALUES ($1)
`

func (q *Queries) CreateProcessedPayment(ctx context.Context, orderID int32) error {
	_, err := q.db.Exec(ctx, createProcessedPayment, orderID)
	return err
}
