// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package query

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO "user" (login, password_hash, role)
VALUES ($1, $2, $3)
RETURNING id
`

type CreateUserParams struct {
	Login        string
	PasswordHash string
	Role         string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (int32, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Login, arg.PasswordHash, arg.Role)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM "user" WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUserByLogin = `-- name: GetUserByLogin :one
SELECT id, login, password_hash, role
FROM "user"
WHERE login = $1
`

func (q *Queries) GetUserByLogin(ctx context.Context, login string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByLogin, login)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Login,
		&i.PasswordHash,
		&i.Role,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE "user"
SET login = $2, password_hash = $3, role = $4
WHERE id = $1
`

type UpdateUserParams struct {
	ID           int32
	Login        string
	PasswordHash string
	Role         string
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.Exec(ctx, updateUser,
		arg.ID,
		arg.Login,
		arg.PasswordHash,
		arg.Role,
	)
	return err
}
