// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service

import (
	"auth/internal/model"
	"context"

	mock "github.com/stretchr/testify/mock"
)

// newMockuserStore creates a new instance of mockuserStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockuserStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockuserStore {
	mock := &mockuserStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockuserStore is an autogenerated mock type for the userStore type
type mockuserStore struct {
	mock.Mock
}

type mockuserStore_Expecter struct {
	mock *mock.Mock
}

func (_m *mockuserStore) EXPECT() *mockuserStore_Expecter {
	return &mockuserStore_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type mockuserStore
func (_mock *mockuserStore) Get(ctx context.Context, login string) (model.User, error) {
	ret := _mock.Called(ctx, login)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 model.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (model.User, error)); ok {
		return returnFunc(ctx, login)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) model.User); ok {
		r0 = returnFunc(ctx, login)
	} else {
		r0 = ret.Get(0).(model.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, login)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockuserStore_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type mockuserStore_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - login string
func (_e *mockuserStore_Expecter) Get(ctx interface{}, login interface{}) *mockuserStore_Get_Call {
	return &mockuserStore_Get_Call{Call: _e.mock.On("Get", ctx, login)}
}

func (_c *mockuserStore_Get_Call) Run(run func(ctx context.Context, login string)) *mockuserStore_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockuserStore_Get_Call) Return(user model.User, err error) *mockuserStore_Get_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *mockuserStore_Get_Call) RunAndReturn(run func(ctx context.Context, login string) (model.User, error)) *mockuserStore_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type mockuserStore
func (_mock *mockuserStore) Save(ctx context.Context, user model.User) (model.User, error) {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 model.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.User) (model.User, error)); ok {
		return returnFunc(ctx, user)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.User) model.User); ok {
		r0 = returnFunc(ctx, user)
	} else {
		r0 = ret.Get(0).(model.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model.User) error); ok {
		r1 = returnFunc(ctx, user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockuserStore_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type mockuserStore_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - user model.User
func (_e *mockuserStore_Expecter) Save(ctx interface{}, user interface{}) *mockuserStore_Save_Call {
	return &mockuserStore_Save_Call{Call: _e.mock.On("Save", ctx, user)}
}

func (_c *mockuserStore_Save_Call) Run(run func(ctx context.Context, user model.User)) *mockuserStore_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.User
		if args[1] != nil {
			arg1 = args[1].(model.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockuserStore_Save_Call) Return(user1 model.User, err error) *mockuserStore_Save_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *mockuserStore_Save_Call) RunAndReturn(run func(ctx context.Context, user model.User) (model.User, error)) *mockuserStore_Save_Call {
	_c.Call.Return(run)
	return _c
}
