// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.32.1
// source: stock.proto

package stock

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Product struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price         float64                `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_stock_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_stock_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_stock_proto_rawDescGZIP(), []int{0}
}

func (x *Product) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Product) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type Stock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *Product               `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	Quantity      int64                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Stock) Reset() {
	*x = Stock{}
	mi := &file_stock_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stock) ProtoMessage() {}

func (x *Stock) ProtoReflect() protoreflect.Message {
	mi := &file_stock_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stock.ProtoReflect.Descriptor instead.
func (*Stock) Descriptor() ([]byte, []int) {
	return file_stock_proto_rawDescGZIP(), []int{1}
}

func (x *Stock) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

func (x *Stock) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type SaveProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	ProductId     *int64                 `protobuf:"varint,2,opt,name=product_id,json=productId,proto3,oneof" json:"product_id,omitempty"`
	ProductName   string                 `protobuf:"bytes,3,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	ProductPrice  float64                `protobuf:"fixed64,4,opt,name=product_price,json=productPrice,proto3" json:"product_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveProductRequest) Reset() {
	*x = SaveProductRequest{}
	mi := &file_stock_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveProductRequest) ProtoMessage() {}

func (x *SaveProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stock_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveProductRequest.ProtoReflect.Descriptor instead.
func (*SaveProductRequest) Descriptor() ([]byte, []int) {
	return file_stock_proto_rawDescGZIP(), []int{2}
}

func (x *SaveProductRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *SaveProductRequest) GetProductId() int64 {
	if x != nil && x.ProductId != nil {
		return *x.ProductId
	}
	return 0
}

func (x *SaveProductRequest) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *SaveProductRequest) GetProductPrice() float64 {
	if x != nil {
		return x.ProductPrice
	}
	return 0
}

type SaveProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stock         *Stock                 `protobuf:"bytes,1,opt,name=stock,proto3" json:"stock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveProductResponse) Reset() {
	*x = SaveProductResponse{}
	mi := &file_stock_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveProductResponse) ProtoMessage() {}

func (x *SaveProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stock_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveProductResponse.ProtoReflect.Descriptor instead.
func (*SaveProductResponse) Descriptor() ([]byte, []int) {
	return file_stock_proto_rawDescGZIP(), []int{3}
}

func (x *SaveProductResponse) GetStock() *Stock {
	if x != nil {
		return x.Stock
	}
	return nil
}

type ChangeStockQuantityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	ProductId     int64                  `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	QuantityDelta int64                  `protobuf:"varint,3,opt,name=quantity_delta,json=quantityDelta,proto3" json:"quantity_delta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeStockQuantityRequest) Reset() {
	*x = ChangeStockQuantityRequest{}
	mi := &file_stock_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeStockQuantityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeStockQuantityRequest) ProtoMessage() {}

func (x *ChangeStockQuantityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stock_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeStockQuantityRequest.ProtoReflect.Descriptor instead.
func (*ChangeStockQuantityRequest) Descriptor() ([]byte, []int) {
	return file_stock_proto_rawDescGZIP(), []int{4}
}

func (x *ChangeStockQuantityRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ChangeStockQuantityRequest) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *ChangeStockQuantityRequest) GetQuantityDelta() int64 {
	if x != nil {
		return x.QuantityDelta
	}
	return 0
}

type ChangeStockQuantityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stock         *Stock                 `protobuf:"bytes,1,opt,name=stock,proto3" json:"stock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeStockQuantityResponse) Reset() {
	*x = ChangeStockQuantityResponse{}
	mi := &file_stock_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeStockQuantityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeStockQuantityResponse) ProtoMessage() {}

func (x *ChangeStockQuantityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stock_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeStockQuantityResponse.ProtoReflect.Descriptor instead.
func (*ChangeStockQuantityResponse) Descriptor() ([]byte, []int) {
	return file_stock_proto_rawDescGZIP(), []int{5}
}

func (x *ChangeStockQuantityResponse) GetStock() *Stock {
	if x != nil {
		return x.Stock
	}
	return nil
}

type ReserveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	OrderId       int64                  `protobuf:"varint,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	ProductId     int64                  `protobuf:"varint,3,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      int64                  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveRequest) Reset() {
	*x = ReserveRequest{}
	mi := &file_stock_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveRequest) ProtoMessage() {}

func (x *ReserveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stock_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveRequest.ProtoReflect.Descriptor instead.
func (*ReserveRequest) Descriptor() ([]byte, []int) {
	return file_stock_proto_rawDescGZIP(), []int{6}
}

func (x *ReserveRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ReserveRequest) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *ReserveRequest) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *ReserveRequest) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type ReserveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stock         *Stock                 `protobuf:"bytes,1,opt,name=stock,proto3" json:"stock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveResponse) Reset() {
	*x = ReserveResponse{}
	mi := &file_stock_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveResponse) ProtoMessage() {}

func (x *ReserveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stock_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveResponse.ProtoReflect.Descriptor instead.
func (*ReserveResponse) Descriptor() ([]byte, []int) {
	return file_stock_proto_rawDescGZIP(), []int{7}
}

func (x *ReserveResponse) GetStock() *Stock {
	if x != nil {
		return x.Stock
	}
	return nil
}

type GetStockInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int64                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStockInfoRequest) Reset() {
	*x = GetStockInfoRequest{}
	mi := &file_stock_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStockInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStockInfoRequest) ProtoMessage() {}

func (x *GetStockInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stock_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStockInfoRequest.ProtoReflect.Descriptor instead.
func (*GetStockInfoRequest) Descriptor() ([]byte, []int) {
	return file_stock_proto_rawDescGZIP(), []int{8}
}

func (x *GetStockInfoRequest) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

type GetStockInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stock         *Stock                 `protobuf:"bytes,1,opt,name=stock,proto3" json:"stock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStockInfoResponse) Reset() {
	*x = GetStockInfoResponse{}
	mi := &file_stock_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStockInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStockInfoResponse) ProtoMessage() {}

func (x *GetStockInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stock_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStockInfoResponse.ProtoReflect.Descriptor instead.
func (*GetStockInfoResponse) Descriptor() ([]byte, []int) {
	return file_stock_proto_rawDescGZIP(), []int{9}
}

func (x *GetStockInfoResponse) GetStock() *Stock {
	if x != nil {
		return x.Stock
	}
	return nil
}

type DeleteProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	ProductId     int64                  `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProductRequest) Reset() {
	*x = DeleteProductRequest{}
	mi := &file_stock_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProductRequest) ProtoMessage() {}

func (x *DeleteProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stock_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProductRequest.ProtoReflect.Descriptor instead.
func (*DeleteProductRequest) Descriptor() ([]byte, []int) {
	return file_stock_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteProductRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *DeleteProductRequest) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

type DeleteProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProductResponse) Reset() {
	*x = DeleteProductResponse{}
	mi := &file_stock_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProductResponse) ProtoMessage() {}

func (x *DeleteProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stock_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProductResponse.ProtoReflect.Descriptor instead.
func (*DeleteProductResponse) Descriptor() ([]byte, []int) {
	return file_stock_proto_rawDescGZIP(), []int{11}
}

var File_stock_proto protoreflect.FileDescriptor

const file_stock_proto_rawDesc = "" +
	"\n" +
	"\vstock.proto\x12\x05stock\"C\n" +
	"\aProduct\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x01R\x05price\"M\n" +
	"\x05Stock\x12(\n" +
	"\aproduct\x18\x01 \x01(\v2\x0e.stock.ProductR\aproduct\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x03R\bquantity\"\xa5\x01\n" +
	"\x12SaveProductRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\"\n" +
	"\n" +
	"product_id\x18\x02 \x01(\x03H\x00R\tproductId\x88\x01\x01\x12!\n" +
	"\fproduct_name\x18\x03 \x01(\tR\vproductName\x12#\n" +
	"\rproduct_price\x18\x04 \x01(\x01R\fproductPriceB\r\n" +
	"\v_product_id\"9\n" +
	"\x13SaveProductResponse\x12\"\n" +
	"\x05stock\x18\x01 \x01(\v2\f.stock.StockR\x05stock\"x\n" +
	"\x1aChangeStockQuantityRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\x03R\tproductId\x12%\n" +
	"\x0equantity_delta\x18\x03 \x01(\x03R\rquantityDelta\"A\n" +
	"\x1bChangeStockQuantityResponse\x12\"\n" +
	"\x05stock\x18\x01 \x01(\v2\f.stock.StockR\x05stock\"|\n" +
	"\x0eReserveRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x19\n" +
	"\border_id\x18\x02 \x01(\x03R\aorderId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x03 \x01(\x03R\tproductId\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x03R\bquantity\"5\n" +
	"\x0fReserveResponse\x12\"\n" +
	"\x05stock\x18\x01 \x01(\v2\f.stock.StockR\x05stock\"4\n" +
	"\x13GetStockInfoRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x03R\tproductId\":\n" +
	"\x14GetStockInfoResponse\x12\"\n" +
	"\x05stock\x18\x01 \x01(\v2\f.stock.StockR\x05stock\"K\n" +
	"\x14DeleteProductRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\x03R\tproductId\"\x17\n" +
	"\x15DeleteProductResponse2\x81\x03\n" +
	"\fStockService\x12D\n" +
	"\vSaveProduct\x12\x19.stock.SaveProductRequest\x1a\x1a.stock.SaveProductResponse\x12\\\n" +
	"\x13ChangeStockQuantity\x12!.stock.ChangeStockQuantityRequest\x1a\".stock.ChangeStockQuantityResponse\x128\n" +
	"\aReserve\x12\x15.stock.ReserveRequest\x1a\x16.stock.ReserveResponse\x12G\n" +
	"\fGetStockInfo\x12\x1a.stock.GetStockInfoRequest\x1a\x1b.stock.GetStockInfoResponse\x12J\n" +
	"\rDeleteProduct\x12\x1b.stock.DeleteProductRequest\x1a\x1c.stock.DeleteProductResponseB\x1bZ\x19common/internal/api/stockb\x06proto3"

var (
	file_stock_proto_rawDescOnce sync.Once
	file_stock_proto_rawDescData []byte
)

func file_stock_proto_rawDescGZIP() []byte {
	file_stock_proto_rawDescOnce.Do(func() {
		file_stock_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stock_proto_rawDesc), len(file_stock_proto_rawDesc)))
	})
	return file_stock_proto_rawDescData
}

var file_stock_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_stock_proto_goTypes = []any{
	(*Product)(nil),                     // 0: stock.Product
	(*Stock)(nil),                       // 1: stock.Stock
	(*SaveProductRequest)(nil),          // 2: stock.SaveProductRequest
	(*SaveProductResponse)(nil),         // 3: stock.SaveProductResponse
	(*ChangeStockQuantityRequest)(nil),  // 4: stock.ChangeStockQuantityRequest
	(*ChangeStockQuantityResponse)(nil), // 5: stock.ChangeStockQuantityResponse
	(*ReserveRequest)(nil),              // 6: stock.ReserveRequest
	(*ReserveResponse)(nil),             // 7: stock.ReserveResponse
	(*GetStockInfoRequest)(nil),         // 8: stock.GetStockInfoRequest
	(*GetStockInfoResponse)(nil),        // 9: stock.GetStockInfoResponse
	(*DeleteProductRequest)(nil),        // 10: stock.DeleteProductRequest
	(*DeleteProductResponse)(nil),       // 11: stock.DeleteProductResponse
}
var file_stock_proto_depIdxs = []int32{
	0,  // 0: stock.Stock.product:type_name -> stock.Product
	1,  // 1: stock.SaveProductResponse.stock:type_name -> stock.Stock
	1,  // 2: stock.ChangeStockQuantityResponse.stock:type_name -> stock.Stock
	1,  // 3: stock.ReserveResponse.stock:type_name -> stock.Stock
	1,  // 4: stock.GetStockInfoResponse.stock:type_name -> stock.Stock
	2,  // 5: stock.StockService.SaveProduct:input_type -> stock.SaveProductRequest
	4,  // 6: stock.StockService.ChangeStockQuantity:input_type -> stock.ChangeStockQuantityRequest
	6,  // 7: stock.StockService.Reserve:input_type -> stock.ReserveRequest
	8,  // 8: stock.StockService.GetStockInfo:input_type -> stock.GetStockInfoRequest
	10, // 9: stock.StockService.DeleteProduct:input_type -> stock.DeleteProductRequest
	3,  // 10: stock.StockService.SaveProduct:output_type -> stock.SaveProductResponse
	5,  // 11: stock.StockService.ChangeStockQuantity:output_type -> stock.ChangeStockQuantityResponse
	7,  // 12: stock.StockService.Reserve:output_type -> stock.ReserveResponse
	9,  // 13: stock.StockService.GetStockInfo:output_type -> stock.GetStockInfoResponse
	11, // 14: stock.StockService.DeleteProduct:output_type -> stock.DeleteProductResponse
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_stock_proto_init() }
func file_stock_proto_init() {
	if File_stock_proto != nil {
		return
	}
	file_stock_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stock_proto_rawDesc), len(file_stock_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_stock_proto_goTypes,
		DependencyIndexes: file_stock_proto_depIdxs,
		MessageInfos:      file_stock_proto_msgTypes,
	}.Build()
	File_stock_proto = out.File
	file_stock_proto_goTypes = nil
	file_stock_proto_depIdxs = nil
}
