apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: main-gateway
  namespace: istio-ingress
  labels:
    app: main-gateway
spec:
  gatewayClassName: istio
  listeners:
  - name: main
    port: 8443
    protocol: HTTPS
    hostname: "azazon.com"
    tls:
      mode: Terminate
      certificateRefs:
      - name: temp-tls-secret
        namespace: security
    allowedRoutes:
      namespaces:
        from: Selector
        selector:
          matchLabels:
            kubernetes.io/metadata.name: azazon
